version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 3
    groups:
      actions-minor-and-patch:
        update-types: [minor, patch]
      actions-major:
        update-types: [major]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Europe/London
    open-pull-requests-limit: 3
