"""What the library reads out of a sliced file: estimates, the printer it was
sliced for and the preview image, across text gcode, binary gcode and a
sliced 3mf."""

from __future__ import annotations

import base64
import io
import struct
import zipfile
import zlib

import pytest

from printguard.engine import gcode

PNG = base64.b64decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==")
PNG_B64 = base64.b64encode(PNG).decode()

PRUSA = (
    "; generated by PrusaSlicer 2.8.1 on 2025-01-02 at 10:11:12 UTC\n"
    ";\n"
    "; thumbnail begin 16x16 92\n"
    f"; {PNG_B64[:60]}\n"
    f"; {PNG_B64[60:]}\n"
    "; thumbnail end\n"
    "; thumbnail begin 220x124 4\n"
    "; QklH\n"
    "; thumbnail end\n"
    ";TYPE:Skirt\n"
    "G1 X10 Y10 E1\n"
    "; filament used [mm] = 4123.4\n"
    "; filament used [g] = 12.34\n"
    "; estimated printing time (normal mode) = 1d 1h 2m 3s\n"
    "; estimated printing time (silent mode) = 2d\n"
    "; prusaslicer_config = begin\n"
    "; printer_model = MK4\n"
    "; prusaslicer_config = end\n"
).encode()

BAMBU_PLATE = (
    "; BambuStudio 01.09.05.51\n"
    "; model printing time: 1h 2m 3s; total estimated time: 1h 5m 3s\n"
    "; total filament length [mm] : 5000.5\n"
    "; total filament weight [g] : 20.5\n"
    "G1 X1\n"
    "; printer_model = Bambu Lab X1 Carbon\n"
).encode()

CURA = (
    ";FLAVOR:Marlin\n"
    ";TIME:3723\n"
    ";Filament used: 4.32m\n"
    ";Layer height: 0.2\n"
    ";Generated with Cura_SteamEngine 5.7.0\n"
    ";TARGET_MACHINE.NAME:Creality Ender-3\n"
    "G1 X1\n"
).encode()


def sliced_3mf(plate: int = 1, image: bytes | None = PNG, gcode_text: bytes = BAMBU_PLATE) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("3D/3dmodel.model", "<model/>")
        archive.writestr(f"Metadata/plate_{plate}.gcode", gcode_text)
        if image is not None:
            archive.writestr(f"Metadata/plate_{plate}.png", image)
    return buffer.getvalue()


def bgcode(*blocks: bytes, checksum: int = 1) -> bytes:
    return b"GCDE" + struct.pack("<IH", 1, checksum) + b"".join(blocks)


def block(kind: int, params: bytes, body: bytes, compression: int = 0, checksum: bool = True) -> bytes:
    stored = zlib.compress(body) if compression == 1 else body
    header = struct.pack("<HHI", kind, compression, len(body))
    if compression:
        header += struct.pack("<I", len(stored))
    return header + params + stored + (b"\0\0\0\0" if checksum else b"")


def test_prusaslicer_gcode_gives_estimates_printer_and_largest_thumbnail() -> None:
    sliced = gcode.inspect(PRUSA, "gcode")
    assert sliced.meta == {
        "slicer": "PrusaSlicer 2.8.1",
        "time_s": 86400 + 3723,
        "filament_g": 12.34,
        "filament_mm": 4123.4,
        "printer_model": "MK4",
    }
    assert sliced.thumbnail == b"BIG", "the largest preview wins, whatever order they come in"
    assert sliced.thumbnail_type == "image/png"


def test_a_big_file_is_read_at_both_ends() -> None:
    padding = b"G1 X1 Y1 E0.1\n" * (gcode.HEAD_BYTES // 14 + 1)
    sliced = gcode.inspect(PRUSA.split(b";TYPE:Skirt")[0] + padding + PRUSA.split(b"G1 X10 Y10 E1\n")[1], "gcode")
    assert sliced.meta["slicer"] == "PrusaSlicer 2.8.1" and sliced.thumbnail == b"BIG", "the head carries the preview"
    assert sliced.meta["printer_model"] == "MK4" and sliced.meta["time_s"] == 86400 + 3723, "the tail carries the config"


def test_cura_gcode_uses_its_own_keys() -> None:
    sliced = gcode.inspect(CURA, "gcode")
    assert sliced.meta == {
        "slicer": "Cura 5.7.0",
        "time_s": 3723,
        "filament_g": None,
        "filament_mm": 4320.0,
        "printer_model": "Creality Ender-3",
    }
    assert sliced.thumbnail is None


def test_sliced_3mf_reads_its_plate_and_falls_back_to_the_plate_image() -> None:
    sliced = gcode.inspect(sliced_3mf(plate=2), "3mf")
    assert sliced.meta == {
        "slicer": "BambuStudio 01.09.05.51",
        "time_s": 3903,
        "filament_g": 20.5,
        "filament_mm": 5000.5,
        "printer_model": "Bambu Lab X1 Carbon",
    }
    assert sliced.thumbnail == PNG and sliced.thumbnail_type == "image/png"
    assert gcode.plate_gcode(sliced_3mf(plate=2)) == (2, BAMBU_PLATE)


def test_a_thumbnail_inside_the_plate_gcode_beats_the_plate_image() -> None:
    sliced = gcode.inspect(sliced_3mf(image=b"PLATE", gcode_text=PRUSA), "3mf")
    assert sliced.thumbnail == b"BIG"


def test_an_unsliced_3mf_and_a_non_zip_are_refused() -> None:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("3D/3dmodel.model", "<model/>")
    with pytest.raises(ValueError, match="not been sliced"):
        gcode.inspect(buffer.getvalue(), "3mf")
    with pytest.raises(ValueError, match="not a zip"):
        gcode.inspect(b"not a zip", "3mf")


def test_binary_gcode_reads_metadata_and_thumbnail_blocks() -> None:
    data = bgcode(
        block(0, struct.pack("<H", 0), b"Producer=PrusaSlicer 2.8.1\n"),
        block(3, struct.pack("<H", 0), b"printer_model=MK4S\nnozzle_diameter=0.4\n"),
        block(5, struct.pack("<HHH", 0, 16, 16), b"SMALL"),
        block(5, struct.pack("<HHH", 1, 320, 240), b"LARGE-JPG"),
        block(5, struct.pack("<HHH", 2, 640, 480), b"QOI-IGNORED"),
        block(4, struct.pack("<H", 0), b"estimated printing time (normal mode)=2h 3m\nfilament used [g]=9.5\nfilament used [mm]=3000\n", compression=1),
        block(2, struct.pack("<H", 0), b"ignored=1\n", compression=3),
        block(1, struct.pack("<H", 0), b"G1 X1\n"),
    )
    sliced = gcode.inspect(data, "bgcode")
    assert sliced.meta == {
        "slicer": "PrusaSlicer 2.8.1",
        "time_s": 7380,
        "filament_g": 9.5,
        "filament_mm": 3000.0,
        "printer_model": "MK4S",
    }
    assert sliced.thumbnail == b"LARGE-JPG" and sliced.thumbnail_type == "image/jpeg"


def test_binary_gcode_without_checksums_and_a_wrong_magic() -> None:
    data = bgcode(block(3, struct.pack("<H", 0), b"printer_model=MINI\n", checksum=False), checksum=0)
    assert gcode.inspect(data, "bgcode").meta["printer_model"] == "MINI"
    with pytest.raises(ValueError, match="not a binary gcode"):
        gcode.inspect(b"G1 X1\n", "bgcode")
