"""What the library reads out of a sliced file: estimates, the printer it was
sliced for and the preview image, across text gcode, binary gcode and a
sliced 3mf."""

from __future__ import annotations

import base64
import hashlib
import io
import struct
import zipfile
import zlib

import pytest

from printguard.engine import gcode

PNG = base64.b64decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==")
PNG_B64 = base64.b64encode(PNG).decode()

PRUSA = (
    "; generated by PrusaSlicer 2.8.1 on 2025-01-02 at 10:11:12 UTC\n"
    ";\n"
    "; thumbnail begin 16x16 92\n"
    f"; {PNG_B64[:60]}\n"
    f"; {PNG_B64[60:]}\n"
    "; thumbnail end\n"
    "; thumbnail begin 220x124 4\n"
    "; QklH\n"
    "; thumbnail end\n"
    ";TYPE:Skirt\n"
    "G1 X10 Y10 E1\n"
    "; filament used [mm] = 4123.4\n"
    "; filament used [g] = 12.34\n"
    "; estimated printing time (normal mode) = 1d 1h 2m 3s\n"
    "; estimated printing time (silent mode) = 2d\n"
    "; prusaslicer_config = begin\n"
    "; printer_model = MK4\n"
    "; prusaslicer_config = end\n"
).encode()

BAMBU_PLATE = (
    "; BambuStudio 01.09.05.51\n"
    "; model printing time: 1h 2m 3s; total estimated time: 1h 5m 3s\n"
    "; total filament length [mm] : 5000.5\n"
    "; total filament weight [g] : 20.5\n"
    "G1 X1\n"
    "; printer_model = Bambu Lab X1 Carbon\n"
).encode()

CURA = (
    ";FLAVOR:Marlin\n"
    ";TIME:3723\n"
    ";Filament used: 4.32m\n"
    ";Layer height: 0.2\n"
    ";Generated with Cura_SteamEngine 5.7.0\n"
    ";TARGET_MACHINE.NAME:Creality Ender-3\n"
    "G1 X1\n"
).encode()


PRUSA_HEATED = (
    "; generated by PrusaSlicer 2.8.1\n"
    "M140 S60\n"
    "M104 T0 S170\n"
    "M109 T0 R170\n"
    "M190 S60\n"
    "M109 S215\n"
    "G1 X1 E1\n"
    "M104 S210 ; layer 2\n"
    "M104 S0\n"
    "M140 S0\n"
    "; first_layer_bed_temperature = 60\n"
    "; bed_temperature = 60\n"
    "; first_layer_temperature = 215,215\n"
    "; temperature = 210,210\n"
).encode()

BAMBU_HEATED = (
    "; BambuStudio 01.09.05.51\n"
    "M140 S55\n"
    "M104 S140\n"
    "M190 S55\n"
    "M109 S250\n"
    "M109 S220\n"
    "G1 X1\n"
    "M140 S0\n"
    "; hot_plate_temp_initial_layer = 55\n"
    "; nozzle_temperature = 220\n"
    "; nozzle_temperature_initial_layer = 220\n"
).encode()


def bambu_two_filaments(weights: str, first_layer: int) -> bytes:
    """A Bambu Studio or Orca plate from a project with PLA in slot 1 and PETG in slot 2."""
    return (
        "; BambuStudio 01.09.07.52\n"
        f"; total filament weight [g] : {weights}\n"
        "; nozzle_temperature = 215,245\n"
        "; nozzle_temperature_initial_layer = 225,255\n"
        "M104 S140 ; probe\n"
        "M109 S250 ; flush\n"
        f"M109 S{first_layer}\n"
        "G1 X1 E1\n"
        f"M104 S{first_layer - 10} ; layer 2\n"
        "M104 S0\n"
    ).encode()


PRUSA_SECOND_EXTRUDER = (
    "; generated by PrusaSlicer 2.8.1\n"
    "M140 S85\n"
    "M190 S85\n"
    "M104 T0 S215\n"
    "M109 T1 S240\n"
    "G1 X1 E1\n"
    "M104 T1 S245\n"
    "M104 T0 S0\n"
    "M104 S0\n"
    "; filament used [mm] = 0.00, 2811.45\n"
    "; first_layer_bed_temperature = 60,85\n"
    "; bed_temperature = 60,85\n"
    "; first_layer_temperature = 215,240\n"
    "; temperature = 210,245\n"
).encode()


def sliced_3mf(plate: int = 1, image: bytes | None = PNG, gcode_text: bytes = BAMBU_PLATE, checksum: bool = False) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("3D/3dmodel.model", "<model/>")
        if checksum:
            archive.writestr(f"Metadata/plate_{plate}.gcode.md5", hashlib.md5(gcode_text).hexdigest().upper())
        archive.writestr(f"Metadata/plate_{plate}.gcode", gcode_text)
        if image is not None:
            archive.writestr(f"Metadata/plate_{plate}.png", image)
    return buffer.getvalue()


def bgcode(*blocks: bytes, checksum: int = 1) -> bytes:
    return b"GCDE" + struct.pack("<IH", 1, checksum) + b"".join(blocks)


def block(kind: int, params: bytes, body: bytes, compression: int = 0, checksum: bool = True) -> bytes:
    stored = zlib.compress(body) if compression == 1 else body
    header = struct.pack("<HHI", kind, compression, len(body))
    if compression:
        header += struct.pack("<I", len(stored))
    return header + params + stored + (b"\0\0\0\0" if checksum else b"")


def test_prusaslicer_gcode_gives_estimates_printer_and_largest_thumbnail() -> None:
    sliced = gcode.inspect(PRUSA, "gcode")
    assert sliced.meta == {
        "slicer": "PrusaSlicer 2.8.1",
        "time_s": 86400 + 3723,
        "filament_g": 12.34,
        "filament_mm": 4123.4,
        "printer_model": "MK4",
        "nozzle": None,
        "bed": None,
    }
    assert sliced.thumbnail == b"BIG", "the largest preview wins, whatever order they come in"
    assert sliced.thumbnail_type == "image/png"


def test_a_big_file_is_read_at_both_ends() -> None:
    padding = b"G1 X1 Y1 E0.1\n" * (gcode.HEAD_BYTES // 14 + 1)
    sliced = gcode.inspect(PRUSA.split(b";TYPE:Skirt")[0] + padding + PRUSA.split(b"G1 X10 Y10 E1\n")[1], "gcode")
    assert sliced.meta["slicer"] == "PrusaSlicer 2.8.1" and sliced.thumbnail == b"BIG", "the head carries the preview"
    assert sliced.meta["printer_model"] == "MK4" and sliced.meta["time_s"] == 86400 + 3723, "the tail carries the config"


def test_cura_gcode_uses_its_own_keys() -> None:
    sliced = gcode.inspect(CURA, "gcode")
    assert sliced.meta == {
        "slicer": "Cura 5.7.0",
        "time_s": 3723,
        "filament_g": None,
        "filament_mm": 4320.0,
        "printer_model": "Creality Ender-3",
        "nozzle": None,
        "bed": None,
    }
    assert sliced.thumbnail is None


def test_sliced_3mf_reads_its_plate_and_falls_back_to_the_plate_image() -> None:
    sliced = gcode.inspect(sliced_3mf(plate=2), "3mf")
    assert sliced.meta == {
        "slicer": "BambuStudio 01.09.05.51",
        "time_s": 3903,
        "filament_g": 20.5,
        "filament_mm": 5000.5,
        "printer_model": "Bambu Lab X1 Carbon",
        "nozzle": None,
        "bed": None,
    }
    assert sliced.thumbnail == PNG and sliced.thumbnail_type == "image/png"
    assert gcode.plate_gcode(sliced_3mf(plate=2)) == (2, BAMBU_PLATE)


def test_a_thumbnail_inside_the_plate_gcode_beats_the_plate_image() -> None:
    sliced = gcode.inspect(sliced_3mf(image=b"PLATE", gcode_text=PRUSA), "3mf")
    assert sliced.thumbnail == b"BIG"


def test_an_unsliced_3mf_and_a_non_zip_are_refused() -> None:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        archive.writestr("3D/3dmodel.model", "<model/>")
    with pytest.raises(ValueError, match="not been sliced"):
        gcode.inspect(buffer.getvalue(), "3mf")
    with pytest.raises(ValueError, match="not a zip"):
        gcode.inspect(b"not a zip", "3mf")


def test_binary_gcode_reads_metadata_and_thumbnail_blocks() -> None:
    data = bgcode(
        block(0, struct.pack("<H", 0), b"Producer=PrusaSlicer 2.8.1\n"),
        block(3, struct.pack("<H", 0), b"printer_model=MK4S\nnozzle_diameter=0.4\n"),
        block(5, struct.pack("<HHH", 0, 16, 16), b"SMALL"),
        block(5, struct.pack("<HHH", 1, 320, 240), b"LARGE-JPG"),
        block(5, struct.pack("<HHH", 2, 640, 480), b"QOI-IGNORED"),
        block(4, struct.pack("<H", 0), b"estimated printing time (normal mode)=2h 3m\nfilament used [g]=9.5\nfilament used [mm]=3000\n", compression=1),
        block(2, struct.pack("<H", 0), b"ignored=1\n", compression=3),
        block(1, struct.pack("<H", 0), b"G1 X1\n"),
    )
    sliced = gcode.inspect(data, "bgcode")
    assert sliced.meta == {
        "slicer": "PrusaSlicer 2.8.1",
        "time_s": 7380,
        "filament_g": 9.5,
        "filament_mm": 3000.0,
        "printer_model": "MK4S",
        "nozzle": None,
        "bed": None,
    }
    assert sliced.thumbnail == b"LARGE-JPG" and sliced.thumbnail_type == "image/jpeg"


def test_binary_gcode_without_checksums_and_a_wrong_magic() -> None:
    data = bgcode(block(3, struct.pack("<H", 0), b"printer_model=MINI\n", checksum=False), checksum=0)
    assert gcode.inspect(data, "bgcode").meta["printer_model"] == "MINI"
    with pytest.raises(ValueError, match="not a binary gcode"):
        gcode.inspect(b"G1 X1\n", "bgcode")


def test_binary_gcode_cut_short_or_damaged_is_refused_as_any_other_bad_file() -> None:
    cut_in_a_thumbnail = bgcode(block(5, struct.pack("<HHH", 0, 16, 16), b"SMALL"))[:20]
    not_deflate = bgcode(struct.pack("<HHII", 4, 1, 8, 8) + struct.pack("<H", 0) + b"\xff" * 8)
    for damaged in (gcode.BGCODE_MAGIC, gcode.BGCODE_MAGIC + b"\x01\x00\x00\x00\x01", cut_in_a_thumbnail, not_deflate):
        with pytest.raises(ValueError, match="cut short or damaged"):
            gcode.inspect(damaged, "bgcode")


def test_a_file_that_unpacks_past_the_cap_is_refused_before_it_is_unpacked(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(gcode, "MAX_MEMBER_BYTES", 1024)
    monkeypatch.setattr(gcode, "MAX_BLOCK_BYTES", 1024)
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("Metadata/plate_1.gcode", b"G1 X1\n" * 1024)
    bomb = bgcode(block(4, struct.pack("<H", 0), b"a=" + b"0" * 4096, compression=1))

    with pytest.raises(ValueError, match="unpacks to more than"):
        gcode.inspect(buffer.getvalue(), "3mf")
    with pytest.raises(ValueError, match="unpacks to more than"):
        gcode.retemper(buffer.getvalue(), "3mf", {"nozzle": 210.0})
    with pytest.raises(ValueError, match="inflates to more than"):
        gcode.inspect(bomb, "bgcode")


def test_binary_gcode_whose_blocks_inflate_past_the_cap_between_them_is_refused(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(gcode, "MAX_BLOCK_BYTES", 1024)
    preview = block(5, struct.pack("<HHH", 0, 16, 16), b"\0" * 400, compression=1)
    assert gcode.inspect(bgcode(preview, preview), "bgcode").thumbnail == b"\0" * 400
    with pytest.raises(ValueError, match="inflates to more than"):
        gcode.inspect(bgcode(preview, preview, preview), "bgcode")


def test_a_number_too_large_to_be_one_is_refused() -> None:
    huge = b"9" * 400
    near_the_limit = b",".join([b"9" * 308] * 20)
    for crafted in (
        b"; filament used [g] = " + huge + b"\n",
        b"; filament used [g] = " + near_the_limit + b"\n",
        b"; filament used [mm] = " + huge + b"\n",
        b";TIME:" + huge + b"\n",
        b"M104 S" + huge + b"\n",
        b"M140 S60\n; bed_temperature = " + huge + b"\n",
    ):
        with pytest.raises(ValueError, match="must be a finite number"):
            gcode.inspect(crafted, "gcode")


def test_temperatures_move_together_and_leave_probing_alone() -> None:
    assert gcode.inspect(PRUSA_HEATED, "gcode").meta.items() >= {"nozzle": 215.0, "bed": 60.0}.items()
    moved = gcode.retemper(PRUSA_HEATED, "gcode", {"nozzle": 230, "bed": 70})
    assert moved == (
        "; generated by PrusaSlicer 2.8.1\n"
        "M140 S70\n"
        "M104 T0 S170\n"
        "M109 T0 R170\n"
        "M190 S70\n"
        "M109 S230\n"
        "G1 X1 E1\n"
        "M104 S225 ; layer 2\n"
        "M104 S0\n"
        "M140 S0\n"
        "; first_layer_bed_temperature = 70\n"
        "; bed_temperature = 70\n"
        "; first_layer_temperature = 230,230\n"
        "; temperature = 225,225\n"
    ).encode()
    assert gcode.inspect(moved, "gcode").meta["nozzle"] == 230.0, "the config moves too, so the file reads back as it prints"


def test_a_file_rewritten_a_piece_at_a_time_moves_what_it_would_whole(monkeypatch: pytest.MonkeyPatch) -> None:
    whole = gcode.retemper(PRUSA_HEATED, "gcode", {"nozzle": 230, "bed": 70})
    for piece in (1, 7, len(PRUSA_HEATED) - 1):
        monkeypatch.setattr(gcode, "REWRITE_BYTES", piece)
        assert gcode.retemper(PRUSA_HEATED, "gcode", {"nozzle": 230, "bed": 70}) == whole
        assert gcode.retemper(PRUSA_HEATED.rstrip(b"\n"), "gcode", {"nozzle": 230, "bed": 70}) == whole.rstrip(b"\n")


def test_without_a_slicer_config_the_first_set_point_leads_and_klipper_macros_move() -> None:
    cura = CURA + b"START_PRINT BED_TEMP=60 EXTRUDER_TEMP=205 CHAMBER=40\nM104 S200\nM140 S0\n"
    assert gcode.inspect(cura, "gcode").meta.items() >= {"nozzle": 205.0, "bed": 60.0}.items()
    moved = gcode.retemper(cura, "gcode", {"nozzle": 215})
    assert moved.endswith(b"START_PRINT BED_TEMP=60 EXTRUDER_TEMP=215 CHAMBER=40\nM104 S210\nM140 S0\n")


def test_a_bambu_plate_keeps_its_wipe_and_flush_temperatures_and_its_checksum() -> None:
    archive = sliced_3mf(gcode_text=BAMBU_HEATED, checksum=True)
    assert gcode.inspect(archive, "3mf").meta.items() >= {"nozzle": 220.0, "bed": 55.0}.items()
    moved = gcode.retemper(archive, "3mf", {"nozzle": 240, "bed": 65})
    plate = gcode.plate_gcode(moved)[1]
    assert b"M140 S65\nM104 S140\nM190 S65\nM109 S250\nM109 S240\n" in plate
    assert b"; nozzle_temperature_initial_layer = 240\n" in plate and b"; hot_plate_temp_initial_layer = 55\n" in plate
    with zipfile.ZipFile(io.BytesIO(moved)) as rewritten:
        assert rewritten.read("Metadata/plate_1.gcode.md5") == hashlib.md5(plate).hexdigest().upper().encode()
        assert rewritten.read("Metadata/plate_1.png") == PNG
        assert rewritten.getinfo("Metadata/plate_1.gcode").compress_type == zipfile.ZIP_DEFLATED
    assert gcode.inspect(moved, "3mf").meta.items() >= {"nozzle": 240.0, "bed": 65.0}.items()


def test_a_bambu_plate_printing_its_second_filament_reads_and_moves_that_one() -> None:
    plate = bambu_two_filaments("0.00,8.90", first_layer=255)
    assert gcode.inspect(plate, "gcode").meta["nozzle"] == 255.0
    moved = gcode.retemper(plate, "gcode", {"nozzle": 240})
    assert b"M104 S140 ; probe\nM109 S250 ; flush\nM109 S240\nG1 X1 E1\nM104 S230 ; layer 2\n" in moved
    assert b"; nozzle_temperature = 215,230\n; nozzle_temperature_initial_layer = 225,240\n" in moved
    assert gcode.inspect(moved, "gcode").meta["nozzle"] == 240.0


def test_an_unused_filament_at_the_flush_temperature_is_not_taken_for_the_first_layer() -> None:
    plate = bambu_two_filaments("8.90,0.00", first_layer=225).replace(b"225,255", b"225,250")
    assert gcode.inspect(plate, "gcode").meta["nozzle"] == 225.0
    moved = gcode.retemper(plate, "gcode", {"nozzle": 215})
    assert b"M109 S250 ; flush\nM109 S215\nG1 X1 E1\nM104 S205 ; layer 2\n" in moved
    assert b"; nozzle_temperature = 205,245\n; nozzle_temperature_initial_layer = 215,250\n" in moved


def test_a_print_using_both_filaments_moves_only_the_one_its_first_layer_uses() -> None:
    plate = bambu_two_filaments("3.10,8.90", first_layer=255) + b"M104 S215 ; the other filament\n"
    assert gcode.inspect(plate, "gcode").meta["nozzle"] == 255.0
    moved = gcode.retemper(plate, "gcode", {"nozzle": 260})
    assert b"M109 S250 ; flush\nM109 S260\nG1 X1 E1\nM104 S250 ; layer 2\n" in moved and moved.endswith(b"M104 S215 ; the other filament\n")


def test_prusaslicer_printing_with_its_second_extruder_reads_and_moves_that_one() -> None:
    assert gcode.inspect(PRUSA_SECOND_EXTRUDER, "gcode").meta.items() >= {"nozzle": 240.0, "bed": 85.0}.items()
    moved = gcode.retemper(PRUSA_SECOND_EXTRUDER, "gcode", {"nozzle": 230, "bed": 70})
    assert moved.startswith(b"; generated by PrusaSlicer 2.8.1\nM140 S70\nM190 S70\nM104 T0 S215\nM109 T1 S230\nG1 X1 E1\nM104 T1 S235\n")
    assert moved.endswith(b"; first_layer_bed_temperature = 60,70\n; bed_temperature = 60,70\n; first_layer_temperature = 215,230\n; temperature = 210,235\n")
    assert gcode.inspect(moved, "gcode").meta.items() >= {"nozzle": 230.0, "bed": 70.0}.items()


def test_a_moved_temperature_stops_at_what_the_heater_can_take() -> None:
    moved = gcode.retemper(PRUSA_HEATED.replace(b"S210 ; layer 2", b"S260 ; layer 2").replace(b"210,210", b"260,260"), "gcode", {"nozzle": 340, "bed": 150})
    assert b"M109 S340\nG1 X1 E1\nM104 S350 ; layer 2\n" in moved and b"M190 S150\n" in moved
    assert b"; temperature = 350,350\n" in moved


def test_temperatures_that_cannot_move_are_refused() -> None:
    with pytest.raises(ValueError, match="binary gcode"):
        gcode.retemper(b"GCDE", "bgcode", {"nozzle": 215})
    with pytest.raises(ValueError, match="never heats the bed"):
        gcode.retemper(b"M109 S215\nG1 X1\n", "gcode", {"bed": 60})
    with pytest.raises(ValueError, match="above 0"):
        gcode.retemper(PRUSA_HEATED, "gcode", {"nozzle": 0})
