"""Reads what a sliced file says about itself.

Every slicer writes its estimates, the printer it sliced for and a preview
image into the file it produces: as comment lines in text gcode, as blocks in
Prusa's binary gcode, and as files inside a sliced Bambu Studio or Orca 3mf.
This pulls those out so the library can show a print without rendering it.
Nothing here touches a platform.
"""

from __future__ import annotations

import base64
import io
import re
import struct
import zipfile
import zlib
from dataclasses import dataclass
from typing import Any, Callable

HEAD_BYTES = 4 * 1024 * 1024
TAIL_BYTES = 512 * 1024
PLATE_GCODE = re.compile(r"^Metadata/plate_(\d+)\.gcode$")
PLATE_IMAGE = "Metadata/plate_{plate}.png"
BGCODE_MAGIC = b"GCDE"
IMAGE_TYPES = {"png": "image/png", "jpg": "image/jpeg"}

_COMMENT = re.compile(rb"^;[^\r\n]*", re.M)
_SLICER = re.compile(r"^;\s*(?:generated by |Generated with )?(PrusaSlicer|OrcaSlicer|SuperSlicer|BambuStudio|Cura)(?:_SteamEngine)? ([\w.]+)")
_THUMBNAIL_BEGIN = re.compile(r"^; thumbnail(?:_(JPG|QOI))? begin (\d+)x(\d+)")
_THUMBNAIL_END = re.compile(r"^; thumbnail(?:_(?:JPG|QOI))? end")
_DURATION = re.compile(r"(\d+)\s*([dhms])")
_LENGTH = re.compile(r"(\d+(?:\.\d+)?)\s*(mm|cm|m)?")
_NUMBER = re.compile(r"\d+(?:\.\d+)?")
_BGCODE_THUMBNAIL = 5
_BGCODE_GCODE = 1
_BGCODE_METADATA = (0, 3, 4)
_BGCODE_IMAGE_TYPES = {0: IMAGE_TYPES["png"], 1: IMAGE_TYPES["jpg"]}
_BGCODE_DEFLATE = 1

_TIME_KEYS = ("total estimated time", "estimated printing time (normal mode)", "TIME", "PRINT.TIME")
_GRAMS_KEYS = ("total filament weight [g]", "total filament used [g]", "filament used [g]")
_LENGTH_KEYS = ("total filament length [mm]", "filament used [mm]", "Filament used")
_PRINTER_KEYS = ("printer_model", "TARGET_MACHINE.NAME")
_SLICER_KEYS = ("Producer",)


@dataclass
class Sliced:
    """What a sliced file says about itself.

    Attributes:
        meta: The slicer, the estimated time in seconds, the filament in grams
            and in millimetres, and the printer model it was sliced for, each
            None where the file does not say.
        thumbnail: The largest preview image the file carries, or None.
        thumbnail_type: The image's media type.
    """

    meta: dict[str, Any]
    thumbnail: bytes | None = None
    thumbnail_type: str | None = None


def inspect(data: bytes, ext: str) -> Sliced:
    """Reads a sliced file's estimates and preview.

    Args:
        data: The whole file.
        ext: Its format, one of the library's accepted extensions.

    Returns:
        What the file says about itself.

    Raises:
        ValueError: If a 3mf carries no sliced plate, or a bgcode file is not one.
    """
    if ext == "3mf":
        plate, gcode = plate_gcode(data)
        sliced = _text(gcode)
        if sliced.thumbnail is None:
            image = _member(data, PLATE_IMAGE.format(plate=plate))
            if image:
                sliced.thumbnail, sliced.thumbnail_type = image, IMAGE_TYPES["png"]
        return sliced
    if ext == "bgcode":
        return _binary(data)
    return _text(data)


def plate_gcode(data: bytes) -> tuple[int, bytes]:
    """Finds the first sliced plate inside a Bambu Studio or Orca 3mf.

    Returns:
        The plate number and its gcode.

    Raises:
        ValueError: If the file is not a zip or holds no plate gcode, which is
            what an unsliced project looks like.
    """
    try:
        with zipfile.ZipFile(io.BytesIO(data)) as archive:
            plates = sorted((int(m.group(1)), name) for name in archive.namelist() if (m := PLATE_GCODE.match(name)))
            if not plates:
                raise ValueError("this 3mf has not been sliced, export it from Bambu Studio or Orca with the gcode included")
            plate, name = plates[0]
            return plate, archive.read(name)
    except zipfile.BadZipFile as exc:
        raise ValueError("this 3mf is not a zip archive") from exc


def _member(data: bytes, name: str) -> bytes | None:
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        return archive.read(name) if name in archive.namelist() else None


def _text(data: bytes) -> Sliced:
    """Reads the comment lines of text gcode.

    Previews and header estimates sit at the top of the file and PrusaSlicer
    writes its estimates and config at the bottom, so only the head and tail
    are scanned and a large file costs nothing extra.
    """
    if len(data) > HEAD_BYTES + TAIL_BYTES:
        data = data[:HEAD_BYTES] + b"\n" + data[-TAIL_BYTES:]
    found: dict[str, str] = {}
    slicer: str | None = None
    thumbnails: list[tuple[int, str, bytes]] = []
    collecting: tuple[int, str, list[str]] | None = None
    for match in _COMMENT.finditer(data):
        line = match.group().decode("utf-8", "replace")
        if collecting is not None:
            if _THUMBNAIL_END.match(line):
                area, media, lines = collecting
                collecting = None
                try:
                    thumbnails.append((area, media, base64.b64decode("".join(lines), validate=True)))
                except ValueError:
                    pass
            else:
                collecting[2].append(line[1:].strip())
            continue
        begin = _THUMBNAIL_BEGIN.match(line)
        if begin:
            media = IMAGE_TYPES["jpg"] if begin.group(1) == "JPG" else IMAGE_TYPES["png"] if begin.group(1) is None else None
            if media:
                collecting = (int(begin.group(2)) * int(begin.group(3)), media, [])
            continue
        if slicer is None and (named := _SLICER.match(line)):
            slicer = f"{named.group(1)} {named.group(2)}"
            continue
        for segment in line[1:].split(";"):
            key, separator, value = segment.partition("=") if "=" in segment else segment.partition(":")
            if separator:
                found.setdefault(key.strip(), value.strip())
    return _sliced(found, slicer, thumbnails)


def _binary(data: bytes) -> Sliced:
    """Reads the metadata and thumbnail blocks of Prusa binary gcode.

    Blocks come in a fixed order with the gcode last, so reading stops there.
    Metadata is INI text, compressed with deflate at most; anything packed
    with heatshrink is skipped rather than decoded.
    """
    if data[:4] != BGCODE_MAGIC:
        raise ValueError("this is not a binary gcode file")
    checksum = struct.unpack_from("<H", data, 8)[0]
    offset = 10
    found: dict[str, str] = {}
    thumbnails: list[tuple[int, str, bytes]] = []
    while offset + 8 <= len(data):
        kind, compression, size = struct.unpack_from("<HHI", data, offset)
        offset += 8
        if compression:
            size = struct.unpack_from("<I", data, offset)[0]
            offset += 4
        if kind == _BGCODE_GCODE:
            break
        params = 6 if kind == _BGCODE_THUMBNAIL else 2
        header = data[offset : offset + params]
        body = data[offset + params : offset + params + size]
        offset += params + size + (4 if checksum else 0)
        if compression == _BGCODE_DEFLATE:
            body = zlib.decompress(body)
        elif compression:
            continue
        if kind == _BGCODE_THUMBNAIL:
            image, width, height = struct.unpack("<HHH", header)
            if image in _BGCODE_IMAGE_TYPES:
                thumbnails.append((width * height, _BGCODE_IMAGE_TYPES[image], body))
        elif kind in _BGCODE_METADATA:
            for line in body.decode("utf-8", "replace").splitlines():
                key, separator, value = line.partition("=")
                if separator:
                    found.setdefault(key.strip(), value.strip())
    return _sliced(found, None, thumbnails)


def _sliced(found: dict[str, str], slicer: str | None, thumbnails: list[tuple[int, str, bytes]]) -> Sliced:
    meta = {
        "slicer": slicer or _first(found, _SLICER_KEYS, str),
        "time_s": _first(found, _TIME_KEYS, _seconds),
        "filament_g": _first(found, _GRAMS_KEYS, _grams),
        "filament_mm": _first(found, _LENGTH_KEYS, _millimetres),
        "printer_model": _first(found, _PRINTER_KEYS, lambda value: value.strip('"')),
    }
    if not thumbnails:
        return Sliced(meta)
    _, media, image = max(thumbnails, key=lambda t: t[0])
    return Sliced(meta, image, media)


def _first(found: dict[str, str], keys: tuple[str, ...], parse: Callable[[str], Any]) -> Any:
    for key in keys:
        if found.get(key):
            parsed = parse(found[key])
            if parsed is not None:
                return parsed
    return None


def _seconds(value: str) -> int | None:
    units = {"d": 86400, "h": 3600, "m": 60, "s": 1}
    parts = _DURATION.findall(value)
    if parts:
        return sum(int(amount) * units[unit] for amount, unit in parts)
    return int(float(value)) if _NUMBER.fullmatch(value.strip()) else None


def _grams(value: str) -> float | None:
    amounts = _NUMBER.findall(value)
    return round(sum(float(amount) for amount in amounts), 2) if amounts else None


def _millimetres(value: str) -> float | None:
    scale = {None: 1.0, "mm": 1.0, "cm": 10.0, "m": 1000.0}
    amounts = _LENGTH.findall(value)
    total = sum(float(amount) * scale[unit or None] for amount, unit in amounts)
    return round(total, 1) if amounts else None
