"""Reads what a sliced file says about itself.

Every slicer writes its estimates, the printer it sliced for and a preview
image into the file it produces: as comment lines in text gcode, as blocks in
Prusa's binary gcode, and as files inside a sliced Bambu Studio or Orca 3mf.
This pulls those out so the library can show a print without rendering it, and
moves the temperatures a file prints at when the slicer got them wrong.
Nothing here touches a platform.
"""

from __future__ import annotations

import base64
import hashlib
import io
import re
import struct
import sys
import zipfile
import zlib
from dataclasses import dataclass
from typing import Any, Callable, Iterator

from .bounds import HEATER_MAX, clamp

HEAD_BYTES = 4 * 1024 * 1024
TAIL_BYTES = 512 * 1024
MAX_MEMBER_BYTES = 512 * 1024 * 1024
"""How large one file inside a 3mf may unpack to, which is what an upload itself is capped at."""
MAX_BLOCK_BYTES = 16 * 1024 * 1024
"""How much the metadata and thumbnail blocks of one binary gcode file may inflate to between them."""
REWRITE_BYTES = 1024 * 1024
"""About how much text gcode is rewritten at a time, so memory and the interpreter lock are held a piece at a time."""
PLATE_GCODE = re.compile(r"^Metadata/plate_(\d+)\.gcode$")
PLATE_GCODE_NAME = "Metadata/plate_{plate}.gcode"
PLATE_IMAGE = "Metadata/plate_{plate}.png"
BGCODE_MAGIC = b"GCDE"
IMAGE_TYPES = {"png": "image/png", "jpg": "image/jpeg"}

_COMMENT = re.compile(rb"^;[^\r\n]*", re.M)
_SLICER = re.compile(r"^;\s*(?:generated by |Generated with )?(PrusaSlicer|OrcaSlicer|SuperSlicer|BambuStudio|Cura)(?:_SteamEngine)? ([\w.]+)")
_THUMBNAIL_BEGIN = re.compile(r"^; thumbnail(?:_(JPG|QOI))? begin (\d+)x(\d+)")
_THUMBNAIL_END = re.compile(r"^; thumbnail(?:_(?:JPG|QOI))? end")
_DURATION = re.compile(r"(\d+)\s*([dhms])")
_LENGTH = re.compile(r"(\d+(?:\.\d+)?)\s*(mm|cm|m)?")
_NUMBER = re.compile(r"\d+(?:\.\d+)?")
_BGCODE_THUMBNAIL = 5
_BGCODE_GCODE = 1
_BGCODE_METADATA = (0, 3, 4)
_BGCODE_IMAGE_TYPES = {0: IMAGE_TYPES["png"], 1: IMAGE_TYPES["jpg"]}
_BGCODE_DEFLATE = 1

_TIME_KEYS = ("total estimated time", "estimated printing time (normal mode)", "TIME", "PRINT.TIME")
_GRAMS_KEYS = ("total filament weight [g]", "total filament used [g]", "filament used [g]")
_LENGTH_KEYS = ("total filament length [mm]", "filament used [mm]", "Filament used")
_PRINTER_KEYS = ("printer_model", "TARGET_MACHINE.NAME")
_SLICER_KEYS = ("Producer",)
_TEMPERATURE_KEYS = {
    "nozzle": ("first_layer_temperature", "nozzle_temperature_initial_layer", "temperature", "nozzle_temperature"),
    "bed": ("first_layer_bed_temperature", "bed_temperature"),
}
_USAGE_KEYS = ("total filament length [mm]", "filament used [mm]", "total filament weight [g]", "filament used [g]")
_DEGREES = rb"\d+(?:\.\d+)?"
_SETPOINT = {
    "nozzle": re.compile(rb"(\nM10[49]\b[^;\n]*?[ \t]S)(" + _DEGREES + rb")"),
    "bed": re.compile(rb"(\nM1[49]0\b[^;\n]*?[ \t]S)(" + _DEGREES + rb")"),
}
_MACRO = re.compile(rb"^[A-Za-z_]{2}[A-Za-z0-9_]*[ \t][^;\n]*", re.M)
_MACRO_PARAM = {
    "nozzle": re.compile(rb"(?<=[ \t])((?:EXTRUDER|HOTEND|NOZZLE)(?:_TEMP(?:ERATURE)?)?=)(" + _DEGREES + rb")", re.I),
    "bed": re.compile(rb"(?<=[ \t])(BED(?:_TEMP(?:ERATURE)?)?=)(" + _DEGREES + rb")", re.I),
}
_CONFIG = {
    heater: re.compile(rb"(\n; (?:" + b"|".join(key.encode() for key in keys) + rb") = )(" + _DEGREES + rb"(?:," + _DEGREES + rb")*)")
    for heater, keys in _TEMPERATURE_KEYS.items()
}


@dataclass
class Sliced:
    """What a sliced file says about itself.

    Attributes:
        meta: The slicer, the estimated time in seconds, the filament in grams
            and in millimetres, the printer model it was sliced for and the
            first layer's nozzle and bed temperatures, each None where the file
            does not say. Binary gcode never reports a temperature, since its
            temperatures cannot be moved.
        thumbnail: The largest preview image the file carries, or None.
        thumbnail_type: The image's media type.
    """

    meta: dict[str, Any]
    thumbnail: bytes | None = None
    thumbnail_type: str | None = None


def inspect(data: bytes, ext: str) -> Sliced:
    """Reads a sliced file's estimates and preview.

    Args:
        data: The whole file.
        ext: Its format, one of the library's accepted extensions.

    Returns:
        What the file says about itself.

    Raises:
        ValueError: If a 3mf carries no sliced plate, a bgcode file is not one or
            is cut short, or either unpacks to more than a sliced file should.
    """
    if ext == "3mf":
        plate, gcode = plate_gcode(data)
        sliced = _text(gcode)
        if sliced.thumbnail is None:
            image = _member(data, PLATE_IMAGE.format(plate=plate))
            if image:
                sliced.thumbnail, sliced.thumbnail_type = image, IMAGE_TYPES["png"]
        return sliced
    if ext == "bgcode":
        return _binary(data)
    return _text(data)


def retemper(data: bytes, ext: str, targets: dict[str, float]) -> bytes:
    """Moves a sliced file's print temperatures so its first layer heats to each target.

    Every set-point at one of the print temperatures of the filament printing
    the first layer moves by the same amount, so a hotter first layer stays
    hotter, while another filament's temperatures and the ones a start gcode
    probes or wipes at stay where they are. Nothing moves past the heater's
    maximum. A file whose slicer lists no print temperatures has every
    non-zero set-point moved.

    Args:
        data: The whole file.
        ext: Its format.
        targets: First-layer temperature in degrees Celsius per heater.

    Returns:
        The file with its temperatures moved.

    Raises:
        ValueError: If the file is binary gcode, never heats a heater named, or
            a target is not above zero.
    """
    if ext == "bgcode":
        raise ValueError("binary gcode's temperatures can't be changed, export it as text gcode instead")
    if ext == "3mf":
        return _replace_plate(data, lambda plate: retemper(plate, "gcode", targets))
    found = _scan(data)[0]
    moves: dict[str, tuple[set[float] | None, float]] = {}
    for heater, target in targets.items():
        first, listed = _temperature(data, found, heater)
        if first is None:
            raise ValueError(f"this file never heats the {heater}")
        if target <= 0:
            raise ValueError(f"a print needs its {heater} above 0°C")
        moves[heater] = (listed, target - first)
    output = io.BytesIO()
    for lines in _whole_lines(data):
        for heater, (listed, delta) in moves.items():
            lines = _shift(lines, heater, listed, delta)
        output.write(lines)
    return output.getvalue()


def plate_gcode(data: bytes) -> tuple[int, bytes]:
    """Finds the first sliced plate inside a Bambu Studio or Orca 3mf.

    Returns:
        The plate number and its gcode.

    Raises:
        ValueError: If the file is not a zip or holds no plate gcode, which is
            what an unsliced project looks like, or the plate is too large.
    """
    try:
        with zipfile.ZipFile(io.BytesIO(data)) as archive:
            plates = sorted((int(m.group(1)), name) for name in archive.namelist() if (m := PLATE_GCODE.match(name)))
            if not plates:
                raise ValueError("this 3mf has not been sliced, export it from Bambu Studio or Orca with the gcode included")
            plate, name = plates[0]
            return plate, _unpacked(archive, name)
    except zipfile.BadZipFile as exc:
        raise ValueError("this 3mf is not a zip archive") from exc


def _unpacked(archive: zipfile.ZipFile, name: str) -> bytes:
    """Reads one file out of a 3mf, refusing one that would unpack past the cap."""
    if archive.getinfo(name).file_size > MAX_MEMBER_BYTES:
        raise ValueError(f"{name} in this 3mf unpacks to more than {MAX_MEMBER_BYTES // 1024 // 1024} MB")
    return archive.read(name)


def _replace_plate(data: bytes, rewrite: Callable[[bytes], bytes]) -> bytes:
    """Rewrites a 3mf's first sliced plate and the checksum Bambu Studio keeps beside it."""
    plate, gcode = plate_gcode(data)
    name = PLATE_GCODE_NAME.format(plate=plate)
    gcode = rewrite(gcode)
    output = io.BytesIO()
    with zipfile.ZipFile(io.BytesIO(data)) as source, zipfile.ZipFile(output, "w") as target:
        for member in source.infolist():
            if member.filename == name:
                body = gcode
            elif member.filename == f"{name}.md5":
                body = hashlib.md5(gcode).hexdigest().upper().encode()
            else:
                body = _unpacked(source, member.filename)
            target.writestr(member, body)
    return output.getvalue()


def _member(data: bytes, name: str) -> bytes | None:
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        return _unpacked(archive, name) if name in archive.namelist() else None


def _text(data: bytes) -> Sliced:
    """Reads the comment lines of text gcode, and the temperatures it heats to."""
    found, slicer, thumbnails = _scan(data)
    temperatures = {heater: _temperature(data, found, heater)[0] for heater in _TEMPERATURE_KEYS}
    return _sliced(found, slicer, thumbnails, temperatures)


def _scan(data: bytes) -> tuple[dict[str, str], str | None, list[tuple[int, str, bytes]]]:
    """Reads the comment lines of text gcode.

    Previews and header estimates sit at the top of the file and PrusaSlicer
    writes its estimates and config at the bottom, so only the head and tail
    are scanned and a large file costs nothing extra.

    Returns:
        Every ``key = value`` or ``key: value`` a comment carries, first one
        winning, the slicer named on a header line, and each preview as its
        pixel area, media type and image.
    """
    if len(data) > HEAD_BYTES + TAIL_BYTES:
        data = data[:HEAD_BYTES] + b"\n" + data[-TAIL_BYTES:]
    found: dict[str, str] = {}
    slicer: str | None = None
    thumbnails: list[tuple[int, str, bytes]] = []
    collecting: tuple[int, str, list[str]] | None = None
    for match in _COMMENT.finditer(data):
        line = match.group().decode("utf-8", "replace")
        if collecting is not None:
            if _THUMBNAIL_END.match(line):
                area, media, lines = collecting
                collecting = None
                try:
                    thumbnails.append((area, media, base64.b64decode("".join(lines), validate=True)))
                except ValueError:
                    pass
            else:
                collecting[2].append(line[1:].strip())
            continue
        begin = _THUMBNAIL_BEGIN.match(line)
        if begin:
            media = IMAGE_TYPES["jpg"] if begin.group(1) == "JPG" else IMAGE_TYPES["png"] if begin.group(1) is None else None
            if media:
                collecting = (int(begin.group(2)) * int(begin.group(3)), media, [])
            continue
        if slicer is None and (named := _SLICER.match(line)):
            slicer = f"{named.group(1)} {named.group(2)}"
            continue
        for segment in line[1:].split(";"):
            key, separator, value = segment.partition("=") if "=" in segment else segment.partition(":")
            if separator:
                found.setdefault(key.strip(), value.strip())
    return found, slicer, thumbnails


def _temperature(data: bytes, found: dict[str, str], heater: str) -> tuple[float | None, set[float] | None]:
    """A heater's first-layer temperature and the print temperatures that go with it.

    A slicer lists one temperature per filament or extruder in the project,
    whether the print uses it or not, and heats to the one that prints the
    first layer. That filament is the first the gcode heats to among those the
    slicer's own tally says the print uses, since a start gcode also heats to
    flush and probe temperatures that can equal an unused filament's.

    Args:
        data: The whole text gcode.
        found: What its comments carry.
        heater: One of the keys of ``_TEMPERATURE_KEYS``.

    Returns:
        The first-layer temperature, or None when the file never heats the
        heater, and every print temperature the slicer's config lists for the
        filament printing the first layer, or None when it lists none, which
        falls back to the first non-zero set-point.
    """
    reached = _setpoints(data[:HEAD_BYTES], heater)
    listed = [temperatures for key in _TEMPERATURE_KEYS[heater] if any(temperatures := [_number(value) for value in _NUMBER.findall(found.get(key, ""))])]
    if not listed:
        return next((value for value in reached if value), None), None
    first_layer = listed[0]
    heated = [filament for filament, degrees in enumerate(first_layer) if degrees]
    usage = next((used for key in _USAGE_KEYS if len(used := _NUMBER.findall(found.get(key, ""))) == len(first_layer)), [])
    printing = [filament for filament in heated if usage and _number(usage[filament])] or heated
    filament = next((printing[index] for value in reached for index, candidate in enumerate(printing) if first_layer[candidate] == value), printing[0])
    return first_layer[filament], {temperatures[filament] for temperatures in listed if filament < len(temperatures) and temperatures[filament]}


def _setpoints(data: bytes, heater: str) -> Iterator[float]:
    """Every temperature text gcode sets a heater to, in file order.

    A set-point is an ``M104``/``M109`` or ``M140``/``M190`` with an ``S``
    value, or a Klipper macro called with ``EXTRUDER=``, ``HOTEND=``,
    ``NOZZLE=`` or ``BED=``, optionally suffixed ``_TEMP``.
    """
    commands = [(match.start(), match[2]) for match in _SETPOINT[heater].finditer(b"\n" + data)]
    macros = [(line.start() + param.start(), param[2]) for line in _MACRO.finditer(data) for param in _MACRO_PARAM[heater].finditer(line[0])]
    return (_number(value) for _, value in sorted(commands + macros))


def _whole_lines(data: bytes) -> Iterator[bytes]:
    """Cuts text gcode into pieces of about ``REWRITE_BYTES``, each ending where a line does."""
    start = 0
    while start < len(data):
        end = data.find(b"\n", start + REWRITE_BYTES) + 1 or len(data)
        yield data[start:end]
        start = end


def _shift(data: bytes, heater: str, listed: set[float] | None, delta: float) -> bytes:
    """Moves a heater's print temperatures by ``delta``, in its set-points and its config comments, up to the heater's maximum.

    Args:
        data: Whole lines of text gcode.
        heater: One of the keys of ``_TEMPERATURE_KEYS``.
        listed: The print temperatures to move, or None for every non-zero one.
        delta: How far to move them, in degrees Celsius.
    """

    def moved(value: bytes) -> bytes:
        degrees = float(value)
        return b"%g" % max(0.0, min(HEATER_MAX[heater], degrees + delta)) if degrees and (listed is None or degrees in listed) else value

    data = _SETPOINT[heater].sub(lambda match: match[1] + moved(match[2]), b"\n" + data)
    data = _MACRO.sub(lambda line: _MACRO_PARAM[heater].sub(lambda param: param[1] + moved(param[2]), line[0]), data)
    return _CONFIG[heater].sub(lambda match: match[1] + b",".join(moved(value) for value in match[2].split(b",")), data)[1:]


def _binary(data: bytes) -> Sliced:
    """Reads the metadata and thumbnail blocks of Prusa binary gcode.

    Blocks come in a fixed order with the gcode last, so reading stops there.
    Metadata is INI text, compressed with deflate at most; anything packed
    with heatshrink is skipped rather than decoded.

    Raises:
        ValueError: If the file is not binary gcode, is cut short or damaged,
            or its blocks inflate past the cap.
    """
    if data[:4] != BGCODE_MAGIC:
        raise ValueError("this is not a binary gcode file")
    try:
        return _blocks(data)
    except (struct.error, zlib.error) as exc:
        raise ValueError("this binary gcode file is cut short or damaged") from exc


def _blocks(data: bytes) -> Sliced:
    checksum = struct.unpack_from("<H", data, 8)[0]
    offset = 10
    found: dict[str, str] = {}
    thumbnails: list[tuple[int, str, bytes]] = []
    room = MAX_BLOCK_BYTES
    while offset + 8 <= len(data):
        kind, compression, size = struct.unpack_from("<HHI", data, offset)
        offset += 8
        if compression:
            size = struct.unpack_from("<I", data, offset)[0]
            offset += 4
        if kind == _BGCODE_GCODE:
            break
        params = 6 if kind == _BGCODE_THUMBNAIL else 2
        header = data[offset : offset + params]
        body = data[offset + params : offset + params + size]
        offset += params + size + (4 if checksum else 0)
        if compression == _BGCODE_DEFLATE:
            inflater = zlib.decompressobj()
            body = inflater.decompress(body, room + 1)
            room -= len(body)
            if room < 0:
                raise ValueError(f"the metadata and previews of this binary gcode inflates to more than {MAX_BLOCK_BYTES // 1024 // 1024} MB")
        elif compression:
            continue
        if kind == _BGCODE_THUMBNAIL:
            image, width, height = struct.unpack("<HHH", header)
            if image in _BGCODE_IMAGE_TYPES:
                thumbnails.append((width * height, _BGCODE_IMAGE_TYPES[image], body))
        elif kind in _BGCODE_METADATA:
            for line in body.decode("utf-8", "replace").splitlines():
                key, separator, value = line.partition("=")
                if separator:
                    found.setdefault(key.strip(), value.strip())
    return _sliced(found, None, thumbnails, {})


def _sliced(
    found: dict[str, str], slicer: str | None, thumbnails: list[tuple[int, str, bytes]], temperatures: dict[str, float | None]
) -> Sliced:
    meta = {
        "slicer": slicer or _first(found, _SLICER_KEYS, str),
        "time_s": _first(found, _TIME_KEYS, _seconds),
        "filament_g": _first(found, _GRAMS_KEYS, _grams),
        "filament_mm": _first(found, _LENGTH_KEYS, _millimetres),
        "printer_model": _first(found, _PRINTER_KEYS, lambda value: value.strip('"')),
        "nozzle": temperatures.get("nozzle"),
        "bed": temperatures.get("bed"),
    }
    if not thumbnails:
        return Sliced(meta)
    _, media, image = max(thumbnails, key=lambda t: t[0])
    return Sliced(meta, image, media)


def _first(found: dict[str, str], keys: tuple[str, ...], parse: Callable[[str], Any]) -> Any:
    for key in keys:
        if found.get(key):
            parsed = parse(found[key])
            if parsed is not None:
                return parsed
    return None


def _number(value: str | bytes | float) -> float:
    """Reads a number a file wrote, or a total of them.

    Raises:
        ValueError: If it is too large to be one, which would not survive the
            JSON a browser reads the library from.
    """
    return clamp("a number in this file", value, 0.0, sys.float_info.max)


def _seconds(value: str) -> int | None:
    units = {"d": 86400, "h": 3600, "m": 60, "s": 1}
    parts = _DURATION.findall(value)
    if parts:
        return sum(int(amount) * units[unit] for amount, unit in parts)
    return int(_number(value)) if _NUMBER.fullmatch(value.strip()) else None


def _grams(value: str) -> float | None:
    amounts = _NUMBER.findall(value)
    return round(_number(sum(float(amount) for amount in amounts)), 2) if amounts else None


def _millimetres(value: str) -> float | None:
    scale = {None: 1.0, "mm": 1.0, "cm": 10.0, "m": 1000.0}
    amounts = _LENGTH.findall(value)
    total = sum(float(amount) * scale[unit or None] for amount, unit in amounts)
    return round(_number(total), 1) if amounts else None
